FROM registry.access.redhat.com/ubi8/go-toolset:1.18

USER 0

# check if go is FIPS capable
RUN openssl version | grep FIPS
RUN go tool nm $(which go) | grep FIPS

# Bundle the project source in the container
ADD . /app
WORKDIR /app

# Build a binary
RUN go build .

# Expose a port and set the default run command for the container
USER 1001
EXPOSE 8443
#CMD ["./fips-echo-server", "-address", "0.0.0.0:8443", "-fipsMode", "true"]
CMD ["./fips-echo-server", "-address", "0.0.0.0:8443"]